In [1]:
import numpy as np
a=np.array(65)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [3]:
import numpy as np
l=[23.5,56,65.8,98.5]
print("Original list:",l)
a=np.array(l)
print("one-dimensional Numpy array:",a)

Original list: [23.5, 56, 65.8, 98.5]
one-dimensional Numpy array: [23.5 56.  65.8 98.5]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(3,2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,2)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
print(df)

      Series_reference   Period  Data_value Suppressed STATUS   UNITS  \
0          BDCQ.SEA1AA  2011.06     80078.0        NaN      F  Number   
1          BDCQ.SEA1AA  2011.09     78324.0        NaN      F  Number   
2          BDCQ.SEA1AA  2011.12     85850.0        NaN      F  Number   
3          BDCQ.SEA1AA  2012.03     90743.0        NaN      F  Number   
4          BDCQ.SEA1AA  2012.06     81780.0        NaN      F  Number   
...                ...      ...         ...        ...    ...     ...   
22184    BDCQ.SEE3999A  2017.06         NaN          Y      C  Number   
22185    BDCQ.SEE3999A  2017.09         NaN          Y      C  Number   
22186    BDCQ.SEE3999A  2017.12         NaN          Y      C  Number   
22187    BDCQ.SEE3999A  2018.03         NaN          Y      C  Number   
22188    BDCQ.SEE3999A  2018.06         NaN          Y      C  Number   

       Magnitude                         Subject  \
0              0  Business Data Collection - BDC   
1              0  B

In [8]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
print(df.to_string())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [9]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df.head()

Series_reference   Period  Data_value Suppressed STATUS   UNITS  Magnitude  \
0      BDCQ.SEA1AA  2011.06     80078.0        NaN      F  Number          0   
1      BDCQ.SEA1AA  2011.09     78324.0        NaN      F  Number          0   
2      BDCQ.SEA1AA  2011.12     85850.0        NaN      F  Number          0   
3      BDCQ.SEA1AA  2012.03     90743.0        NaN      F  Number          0   
4      BDCQ.SEA1AA  2012.06     81780.0        NaN      F  Number          0   

                          Subject                            Group  \
0  Business Data Collection - BDC  Industry by employment variable   
1  Business Data Collection - BDC  Industry by employment variable   
2  Business Data Collection - BDC  Industry by employment variable   
3  Business Data Collection - BDC  Industry by employment variable   
4  Business Data Collection - BDC  Industry by employment variable   

  Series_title_1                     Series_title_2 Series_title_3  \
0    Filled jobs  Agriculture, Forestry and Fishing         Actual   
1    Filled jobs  Agriculture, Forestry and Fishing         Actual   
2    Filled jobs  Agriculture, Forestry and Fishing         Actual   
3    Filled jobs  Agriculture, Forestry and Fishing         Actual   
4    Filled jobs  Agriculture, Forestry and Fishing         Actual   

   Series_title_4  Series_title_5  
0             NaN             NaN  
1             NaN             NaN  
2             NaN             NaN  
3             NaN             NaN  
4             NaN             NaN

In [10]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df.tail()

Series_reference   Period  Data_value Suppressed STATUS   UNITS  \
22184    BDCQ.SEE3999A  2017.06         NaN          Y      C  Number   
22185    BDCQ.SEE3999A  2017.09         NaN          Y      C  Number   
22186    BDCQ.SEE3999A  2017.12         NaN          Y      C  Number   
22187    BDCQ.SEE3999A  2018.03         NaN          Y      C  Number   
22188    BDCQ.SEE3999A  2018.06         NaN          Y      C  Number   

       Magnitude                         Subject  \
22184          0  Business Data Collection - BDC   
22185          0  Business Data Collection - BDC   
22186          0  Business Data Collection - BDC   
22187          0  Business Data Collection - BDC   
22188          0  Business Data Collection - BDC   

                                              Group  \
22184  Territorial authority by employment variable   
22185  Territorial authority by employment variable   
22186  Territorial authority by employment variable   
22187  Territorial authority by employment variable   
22188  Territorial authority by employment variable   

                               Series_title_1  \
22184  Filled jobs (workplace location based)   
22185  Filled jobs (workplace location based)   
22186  Filled jobs (workplace location based)   
22187  Filled jobs (workplace location based)   
22188  Filled jobs (workplace location based)   

                           Series_title_2 Series_title_3  Series_title_4  \
22184  Area Outside Territorial Authority         Actual             NaN   
22185  Area Outside Territorial Authority         Actual             NaN   
22186  Area Outside Territorial Authority         Actual             NaN   
22187  Area Outside Territorial Authority         Actual             NaN   
22188  Area Outside Territorial Authority         Actual             NaN   

       Series_title_5  
22184             NaN  
22185             NaN  
22186             NaN  
22187             NaN  
22188             NaN

In [11]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22189 entries, 0 to 22188
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Series_reference  22189 non-null  object 
 1   Period            22189 non-null  float64
 2   Data_value        19350 non-null  float64
 3   Suppressed        2839 non-null   object 
 4   STATUS            22189 non-null  object 
 5   UNITS             22189 non-null  object 
 6   Magnitude         22189 non-null  int64  
 7   Subject           22189 non-null  object 
 8   Group             22189 non-null  object 
 9   Series_title_1    22189 non-null  object 
 10  Series_title_2    22189 non-null  object 
 11  Series_title_3    22189 non-null  object 
 12  Series_title_4    0 non-null      float64
 13  Series_title_5    0 non-null      float64
dtypes: float64(4), int64(1), object(9)
memory usage: 2.4+ MB


In [12]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df.describe()

Period    Data_value     Magnitude  Series_title_4  \
count  22189.000000  1.935000e+04  22189.000000             0.0   
mean    2016.896049  7.222688e+04      2.327910             NaN   
std        3.557176  2.089239e+05      2.923813             NaN   
min     2011.060000  1.187001e+00      0.000000             NaN   
25%     2014.060000  1.862571e+03      0.000000             NaN   
50%     2017.060000  1.407000e+04      0.000000             NaN   
75%     2020.060000  6.016300e+04      6.000000             NaN   
max     2023.090000  2.295859e+06      6.000000             NaN   

       Series_title_5  
count             0.0  
mean              NaN  
std               NaN  
min               NaN  
25%               NaN  
50%               NaN  
75%               NaN  
max               NaN

In [13]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df.sample(10)

Series_reference   Period     Data_value Suppressed STATUS   UNITS  \
11490     BDCQ.SED3RDA  2019.06  129185.000000        NaN      F  Number   
1995       BDCQ.SEA1NA  2022.09   98929.000000        NaN      R  Number   
1389       BDCQ.SEA1JA  2021.03   30483.000000        NaN      R  Number   
3078       BDCQ.SEA2AS  2018.06            NaN          Y      R   Value   
18064    BDCQ.SEE2062A  2012.09     276.654729        NaN      F   Value   
16705    BDCQ.SEE2033A  2022.12     660.966056        NaN      R   Value   
18238    BDCQ.SEE2065A  2018.09      23.890274        NaN      F   Value   
14866    BDCQ.SEE1065A  2013.06    1647.000000        NaN      F  Number   
10118     BDCQ.SED2RGT  2011.09            NaN          Y      C   Value   
12485    BDCQ.SEE1016A  2018.03   60358.000000        NaN      F  Number   

       Magnitude                         Subject  \
11490          0  Business Data Collection - BDC   
1995           0  Business Data Collection - BDC   
1389           0  Business Data Collection - BDC   
3078           6  Business Data Collection - BDC   
18064          6  Business Data Collection - BDC   
16705          6  Business Data Collection - BDC   
18238          6  Business Data Collection - BDC   
14866          0  Business Data Collection - BDC   
10118          6  Business Data Collection - BDC   
12485          0  Business Data Collection - BDC   

                                              Group  \
11490                 Region by employment variable   
1995                Industry by employment variable   
1389                Industry by employment variable   
3078                Industry by employment variable   
18064  Territorial authority by employment variable   
16705  Territorial authority by employment variable   
18238  Territorial authority by employment variable   
14866  Territorial authority by employment variable   
10118                 Region by employment variable   
12485  Territorial authority by employment variable   

                               Series_title_1  \
11490  Filled jobs (workplace location based)   
1995                              Filled jobs   
1389                              Filled jobs   
3078                           Total earnings   
18064                          Total earnings   
16705                          Total earnings   
18238                          Total earnings   
14866                             Filled jobs   
10118                          Total earnings   
12485                             Filled jobs   

                                 Series_title_2       Series_title_3  \
11490                             Bay of Plenty               Actual   
1995        Administrative and Support Services               Actual   
1389   Information Media and Telecommunications               Actual   
3078          Agriculture, Forestry and Fishing  Seasonally adjusted   
18064                           Selwyn District               Actual   
16705                     New Plymouth District               Actual   
18238                        Mackenzie District               Actual   
14866                        Mackenzie District               Actual   
10118                                  Taranaki                Trend   
12485                             Hamilton City               Actual   

       Series_title_4  Series_title_5  
11490             NaN             NaN  
1995              NaN             NaN  
1389              NaN             NaN  
3078              NaN             NaN  
18064             NaN             NaN  
16705             NaN             NaN  
18238             NaN             NaN  
14866             NaN             NaN  
10118             NaN             NaN  
12485             NaN             NaN

In [14]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df.isnull()

Series_reference  Period  Data_value  Suppressed  STATUS  UNITS  \
0                 False   False       False        True   False  False   
1                 False   False       False        True   False  False   
2                 False   False       False        True   False  False   
3                 False   False       False        True   False  False   
4                 False   False       False        True   False  False   
...                 ...     ...         ...         ...     ...    ...   
22184             False   False        True       False   False  False   
22185             False   False        True       False   False  False   
22186             False   False        True       False   False  False   
22187             False   False        True       False   False  False   
22188             False   False        True       False   False  False   

       Magnitude  Subject  Group  Series_title_1  Series_title_2  \
0          False    False  False           False           False   
1          False    False  False           False           False   
2          False    False  False           False           False   
3          False    False  False           False           False   
4          False    False  False           False           False   
...          ...      ...    ...             ...             ...   
22184      False    False  False           False           False   
22185      False    False  False           False           False   
22186      False    False  False           False           False   
22187      False    False  False           False           False   
22188      False    False  False           False           False   

       Series_title_3  Series_title_4  Series_title_5  
0               False            True            True  
1               False            True            True  
2               False            True            True  
3               False            True            True  
4               False            True            True  
...               ...             ...             ...  
22184           False            True            True  
22185           False            True            True  
22186           False            True            True  
22187           False            True            True  
22188           False            True            True  

[22189 rows x 14 columns]

In [15]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df.isnull().sum()

Series_reference        0
Period                  0
Data_value           2839
Suppressed          19350
STATUS                  0
UNITS                   0
Magnitude               0
Subject                 0
Group                   0
Series_title_1          0
Series_title_2          0
Series_title_3          0
Series_title_4      22189
Series_title_5      22189
dtype: int64

In [17]:
import pandas as pd
df=pd.read_csv('/content/business-employment-data-september-2023-quarter.zip')
df[4:7]

Series_reference   Period  Data_value Suppressed STATUS   UNITS  Magnitude  \
4      BDCQ.SEA1AA  2012.06     81780.0        NaN      F  Number          0   
5      BDCQ.SEA1AA  2012.09     79261.0        NaN      F  Number          0   
6      BDCQ.SEA1AA  2012.12     87793.0        NaN      F  Number          0   

                          Subject                            Group  \
4  Business Data Collection - BDC  Industry by employment variable   
5  Business Data Collection - BDC  Industry by employment variable   
6  Business Data Collection - BDC  Industry by employment variable   

  Series_title_1                     Series_title_2 Series_title_3  \
4    Filled jobs  Agriculture, Forestry and Fishing         Actual   
5    Filled jobs  Agriculture, Forestry and Fishing         Actual   
6    Filled jobs  Agriculture, Forestry and Fishing         Actual   

   Series_title_4  Series_title_5  
4             NaN             NaN  
5             NaN             NaN  
6             NaN             NaN