In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
func_arr = np.zeros(arr1)
print(func_arr)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [5]:
func_arr = np.ones(arr1)
print(func_arr)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
func_arr = np.full((arr1),9)
print(func_arr)

[[[9 9 9]
  [9 9 9]]]


In [7]:
func_arr = np.arange(2,4,2)
print(func_arr)

[2]


In [8]:
func_arr = np.linspace(2,3,4)
print(func_arr)

[2.         2.33333333 2.66666667 3.        ]


In [9]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[2 4 6]
 [5 7 9]]
[[ 0  0  0]
 [-3 -3 -3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


In [10]:
arr3=np.array([[9],[8],[7]])
print(arr1+arr3)

[[10 11 12]
 [ 9 10 11]
 [ 8  9 10]]


In [11]:
arr = np.array([0,np.pi,np.pi/2])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.ceil(arr))
print(np.sqrt(arr))
print(np.floor(arr))
print(np.round(arr))
print(np.sum(arr))
print(np.sort(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))


[0.0000000e+00 1.2246468e-16 1.0000000e+00]
[ 1.000000e+00 -1.000000e+00  6.123234e-17]
[ 0.00000000e+00 -1.22464680e-16  1.63312394e+16]
[      -inf 1.14472989 0.45158271]
[ 1.         23.14069263  4.81047738]
[0. 4. 2.]
[0.         1.77245385 1.25331414]
[0. 3. 1.]
[0. 3. 2.]
4.71238898038469
[0.         1.57079633 3.14159265]
0.0
3.141592653589793
1.5707963267948966


<ipython-input-11-ae7b324b771a>:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [13]:
arr4=np.arange(10)
reshaped_arr = arr4.reshape((2,5))
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
vstacked=np.vstack((arr1,arr2))
hstacked=np.hstack((arr1,arr2))
split=np.split((hstack),2)
print(vstacked)
print(hstacked)
print(split)

In [15]:
arr5 = np.array([1,2,3,4,5,6,7,8])
print(arr[2])
print(arr[1:3])
print(arr[::2])
print(arr[-1])
indices= [1,4]
print(arr5[indices])

1.5707963267948966
[3.14159265 1.57079633]
[0.         1.57079633]
1.5707963267948966
[2 5]


In [17]:
arr6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr6[:2,:])
print(arr6[:,:2])
print(arr6[-1,:])
print(arr6[:,-1])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
[7 8 9]
[3 6 9]


In [34]:
print(arr5[arr5<7])
print(arr5[arr5>8])


[1 2 3 4 5 6]
[]
